server/auth_app/urls.py
from django.urls import path
from auth_app.views import CustomSignInView
from auth_app.views import CustomSignUpView
from auth_app.views import CustomSignOutView

app_name = 'auth_app'

urlpatterns = [
    path('sign-in/', CustomSignInView.as_view(), name="sign-in"),
    path('sign-up/', CustomSignUpView.as_view(), name="sign-up"),
    path('sign-out/', CustomSignOutView.as_view(), name="sign-out"),
]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('auth/', include('auth_app.urls', namespace='auth_app')),
    path('admin/', admin.site.urls),
]

server/auth_app/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.hashers import make_password


class CustomUser(AbstractUser):
    password = models.CharField(
        _("password"),
        max_length=128,
        default=make_password(settings.AUTH_USER_DEFAULT_PASSWORD)
    )

server/pin_code_app/models.py
from django.db import models
from auth_app.models import CustomUser
from pin_code_app.commons import (
    default_date_plus_five_min,
    default_date,
    default_pin_code
)


class Record(models.Model):
    pin_code = models.CharField(max_length=6, default=default_pin_code)
    created_at = models.DateTimeField(default=default_date)
    use_before = models.DateTimeField(default=default_date_plus_five_min)
    used = models.BooleanField(default=False)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.pin_code

server/auth_app/views.py
from django.shortcuts import render
from django.contrib.auth import (
    authenticate,
    login,
    logout
)
from django.conf import settings
from django.views import View
from pin_code_app.services import (
    add_record,
    users_record_by_pin_code,
    not_used_users_records,
    use_record
)
from auth_app.services import user_by_username


class CustomSignUpView(View):
    def post(self, request, *args, **kwargs):
        username = request.POST.get("username", "")
        user = user_by_username(username=username)
        if user is None:
            return render(
                request=request,
                template_name="auth_app/signin.html"
            )
        pin_code = request.POST.get("pin_code", "")
        records = not_used_users_records(user=user)
        record = users_record_by_pin_code(
            records=records,
            pin_code=pin_code
        )
        if record is None:
            return render(
                request=request,
                template_name="auth_app/signin.html"
            )
        password = settings.AUTH_USER_DEFAULT_PASSWORD
        auth_user = authenticate(
            request=request,
            username=username,
            password=password
        )
        if auth_user is None:
            return render(
                request=request,
                template_name="auth_app/signin.html"
            )
        login(request, auth_user)
        use_record(record=record)
        return render(
                request=request,
                template_name="auth_app/index.html"
            )


class CustomSignOutView(View):
    def get(self, request, *args, **kwargs):
        logout()


class CustomSignInView(View):
    def get(self, request, *args, **kwargs):
        return render(request=request, template_name="auth_app/signin.html")

    def post(self, request, *args, **kwargs):
        username = request.POST.get("username", "")
        user = user_by_username(username=username)
        if user is None:
            return render(
                request=request,
                template_name="auth_app/signin.html"
            )
        add_record(user=user)
        return render(
            request=request,
            template_name="auth_app/signup.html",
            context={"user": user}
        )

server/pin_code_app/views.py
from django.shortcuts import render

# Create your views here.

server/auth_app/templates/auth_app/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{ error }}</h1>
</body>
</html>

server/auth_app/templates/auth_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>hello world</h1>
</body>
</html>

server/auth_app/templates/auth_app/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'auth_app:sign-in' %}" method="post">
        {% csrf_token %}

        <input type="username" name="username">
        <input type="submit">
    </form>
</body>
</html>

server/auth_app/templates/auth_app/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'auth_app:sign-up' %}" method="post">
        {% csrf_token %}

        <input type="text" name="username" value="{{ user.username }}" readonly>
        <input type="text" name="pin_code">
        <input type="submit">
    </form>
</body>
</html>